GET https://groupietrackers.herokuapp.com/api

###

GET "https://groupietrackers.herokuapp.com/api/artists" HTTP/1.1

###

GET "https://groupietrackers.herokuapp.com/api/locations"

###

GET "https://groupietrackers.herokuapp.com/api/dates"

###

GET "https://groupietrackers.herokuapp.com/api/relation"
